### ISSUE TITLE
dohttpreq() / updater not working

### ISSUE THREAD

**Issue by BangL** [blt4linux/blt4l#23] opened 2016-04-23 20:48 UTC
looks like dohttpreq() is not working properly yet. so isnt the updater-feature.

**Comment by RomanHargrave** [comment] 2016-04-23 20:56
Can you provide some more details please?

**Comment by BangL** [comment] 2016-04-23 21:00
not really. it's just that the result callback isnt getting called at all. dohttpreq() does nothing.
no log entries, no nothing.

**Comment by RomanHargrave** [comment] 2016-04-23 21:05
which callback?

can you place a watch on the relevant functions in GDB?

**Comment by Ozymandias117** [comment] 2016-04-23 23:17
I see a handful of issues. I'll push a patch shortly.

**Comment by Ozymandias117** [comment] 2016-04-23 23:57
I have the HTTP issue fixed, although I'm getting a permission denied when attempting to push.
I don't use GitHub much (As you've noticed). From our previous conversations, I was under the impression I should be able to? Should I create a pull request instead?

There appears to be an issue in the unzip code as well, which I haven't fixed yet.

**Comment by RomanHargrave** [comment] 2016-04-24 00:25
Can you tell me what `git remote -v` outputs?

**Comment by Ozymandias117** [comment] 2016-04-24 00:28
Originally, it was
`origin	https://github.com/blt4linux/blt4l.git (fetch)
origin	https://github.com/blt4linux/blt4l.git (push)
`
based off comments on [stackoverflow](https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed) I tried changing it to
`origin	https://Ozymandias117@github.com/blt4linux/blt4l.git (fetch)
origin	https://Ozymandias117@github.com/blt4linux/blt4l.git (push)
`

Stil getting `remote: Permission to blt4linux/blt4l.git denied to Ozymandias117.` either way

**Comment by RomanHargrave** [comment] 2016-04-24 00:31
change https to ssh and see what happens.

you may need to add an ssh key

**Comment by Ozymandias117** [comment] 2016-04-24 00:39
Added an SSH key to my account, switched to
`origin	ssh://Ozymandias117@github.com/blt4linux/blt4l.git (fetch)
origin	ssh://Ozymandias117@github.com/blt4linux/blt4l.git (push)`

Slightly different error, with the same meaning: `ERROR: Permission to blt4linux/blt4l.git denied to Ozymandias117.`

**Comment by RomanHargrave** [comment] 2016-04-24 00:55
that's _really_ odd.

you have member access to all org repos. if leonard can push, you should be able to.

**Comment by RomanHargrave** [comment] 2016-04-24 00:57
please try now

**Comment by Ozymandias117** [comment] 2016-04-24 01:04
There we go! :)

HTTP implementation is in. I was going to start investigating the unzip stuff now.

**Comment by Ozymandias117** [comment] 2016-04-24 01:39
Zip extracting is working in the updater now.
There's still an issue with the fact that the path is being set as, for example, mods/GoonMod/dialogs.
path_is_dir is failing, causing create_file_parent to try to create the directory, even though it already exists. The update still appears to work, just with these silent errors.

**Comment by RomanHargrave** [comment] 2016-04-24 01:55
@Ozymandias117 to clarify, `path_is_dir` called with the path to `mods/GoonMod/dialogs` is returning a nonzero exit status? Is `dialogs` a dir?

**Comment by Ozymandias117** [comment] 2016-04-24 01:56
Yeah, it appears to be. It looked to be failing even when the path was just mods/
I'll double check, though

**Comment by RomanHargrave** [comment] 2016-04-24 01:58
@Ozymandias117 as far as `path_is_dir` is related to `create_file_parent`, if it returns false, it will create the nonexistant directory.

**Comment by RomanHargrave** [comment] 2016-04-24 02:11
I noticed that some of the paths generated contain `//` instead of `/`, while this is perfectly valid, it is not accounted for in `create_file_parent`. I'll go ahead and fix this.

Whether it is the cause of issues with the updater or not, we shall see.

**Comment by Ozymandias117** [comment] 2016-04-24 02:13
I don't think it is. One issue I see is that stat returns 0 on success, which would be false in
`if (stat(path.c_str(), &fileInfo))`

I was trying to verify that changing it to
`if (0 == stat(path.c_str(), &fileInfo))`
fixed it, but I've been running into local problems.

**Comment by Ozymandias117** [comment] 2016-04-24 02:23
Like I said, though. The updates are "working" I'm just concerned these hidden failures could cause other issues in the future.

**Comment by RomanHargrave** [comment] 2016-04-24 02:24
I have tracked down the issue to `stat()` returning a non-zero exit status. Working on it atm.

**Comment by RomanHargrave** [comment] 2016-04-24 02:28
This is certainly strange. `errno` appears to be set to `EAGAIN`.

**Comment by RomanHargrave** [comment] 2016-04-24 02:30
woops.

just remembered the semantics of `if`.

**Comment by RomanHargrave** [comment] 2016-04-24 02:34
@Ozymandias117 @BangL everything should be fine and well now.
before I tag and release, I would appreciate it if you could test this at the latest commit

**Comment by Ozymandias117** [comment] 2016-04-24 02:35
Yeah, the reason I hadn't pushed that change yet is that I don't get any mods with it.
Are you still getting mods?

**Comment by RomanHargrave** [comment] 2016-04-24 02:40
am I still getting mods?
i was able to redownload mods without issue, if you are referring to the updater.

**Comment by Ozymandias117** [comment] 2016-04-24 02:41
No, I mean mods don't load at all for me with that change, which was why I hadn't pushed it. I haven't figured out why I'm not getting anything loading.

**Comment by RomanHargrave** [comment] 2016-04-24 02:41
what change did you make?

**Comment by Ozymandias117** [comment] 2016-04-24 02:42
10 comments ago, where I said stat should return 0 on success.
I then pulled up to master and ran it, since you pushed the same change as I'd said.
For some reason, I'm not getting any mods at all. I'll continue digging.

**Comment by RomanHargrave** [comment] 2016-04-24 02:45
oh hah.

didn't see that comment. yeah. what's going on in your log? if that's the only change you made, then you're the same as I am, effectively. it's odd that blt isn't loading for you

What's your log look like?

**Comment by Ozymandias117** [comment] 2016-04-24 02:47
`09:46:31 PM Info: finding lua functions
09:46:31 PM Info: installing hooks
09:46:31 PM Info: installing BLT LUA API
09:46:31 PM Info: Loading BLT Base
09:46:31 PM Info: luaL_loadfile() = 6
09:46:31 PM Info: lua_pcall(...) = 2
09:46:31 PM Error: Loading BLT Base failed (Runtime Error)
09:46:31 PM Error: attempt to call a string value
`

**Comment by RomanHargrave** [comment] 2016-04-24 02:56
a return value of `6` for `luaL_loadfile()` is not documented, but some discussion on SO (as terrible as it is) suggests that `6` may be a indicate a missing file. What path is being passed to `luaL_loadfile`?

**Comment by Ozymandias117** [comment] 2016-04-24 03:02
Good catch!

That output comes from hook.cc, where we're trying to load mods/base/base.lua

It looks like somewhere in my updater testing, I wound up without a base folder. Like I said earlier, I was pretty sure it was a local issue! :)

**Comment by RomanHargrave** [comment] 2016-04-24 03:08
Closing b/c lgtm

**Closed** 2016-04-24 03:08 UTC
Labels: bug, fixed

**Comment by Ozymandias117** [comment] 2016-04-24 03:14
Same here. With my changes and your change I see no more issues with updating.
