### ISSUE TITLE
BLT DLL Update message

### ISSUE THREAD

**Issue by NoXPhasma** [blt4linux/blt4l#24] opened 2016-04-25 21:33 UTC
Every time when I get to the main menu I get the message that the BLT DLL needs an update and I need to click on "Update later". Even we don't use that on Linux.

However, when I want to update it, it downloads the zip file but hangs at extracting it. I can't stop that update and the only way to stop it, is to kill the game.

I've already tried to exclude it from the automatically update (unchecked it in the BLT options) without success. This is not related to any mods.

Here's a screenshot of that message: https://i.imgur.com/iXxHXbb.jpg

**Comment by RomanHargrave** [comment] 2016-04-25 21:42
What version of BLT are you using?

**Comment by NoXPhasma** [comment] 2016-04-25 21:47
The current [head](https://github.com/blt4linux/blt4l/tree/fb97e85464692977c80b13619005eeb298e9fb47).

**Comment by NoXPhasma** [comment] 2016-04-25 23:53
I've tried now with blt4l_1.2_Ubuntu-trusty.tar.xz, and it is the same behavior.

**Comment by RomanHargrave** [comment] 2016-04-26 00:14
Whis would be an indicator that the ZIP support is not fully compliant, or that a callback is broken, @Ozymandias117. Preferably I or someone else will eventually submit a PR to remove the DLL updater from the shared LUA when using a linux platform.

**Comment by Ozymandias117** [comment] 2016-04-26 03:29
It's a bug down in the shared Lua code.

The DLL update code is all a special case. If it fails, it never calls LuaModUpdates:SetDownloadDialogKey to make that dialog box active again.

If you add `LuaModUpdates:SetDownloadDialogKey( "mod_download_failed", true )` after `log( "[Error] Could not update hook DLL! " .. tostring(hook_error) )` in mods/base/req/update_mods.lua:255 you'll be able to continue with the "failed" update. The issue is that the file doesn't exist, so the rename fails, and the Lua code starts to bail.

**Comment by Ozymandias117** [comment] 2016-04-26 03:30
The reason it shows up at all is because of the mods.txt file in the shared base mod. I've not really come up with a reasonable way to fix that between the two repos.

**Comment by NoXPhasma** [comment] 2016-04-26 15:46
@Ozymandias117 thanks for the hint with the mod.txt, for now we can remove the payday2bltdll part of the updates array as workaround.

Just change this part:
```
	"updates" : [
		{
			"revision" : 12,
			"identifier" : "payday2blt"
		},
		{
			"revision" : "./mods/saves/blt_revision.txt",
			"identifier" : "payday2bltdll",
			"install_dir" : ".",
			"display_name" : "Payday 2 BLT Hook DLL"
		}
	],
```
to
```
	"updates" : [
		{
			"revision" : 12,
			"identifier" : "payday2blt"
		}
	],
```

**Comment by RomanHargrave** [comment] 2016-04-26 19:08
@NoXPhasma since we pull that in from JameWilko's repo, we need to open a PR. The more elegant way to deal with this, which I have opened a PR about, would be to add an `os` property that lets a specific OS be specified for that update item.

**Comment by BangL** [comment] 2016-04-26 22:35
this is a never ending circle:
it would be against the design of the BLT, if you would add this special case.
the blt is designed to use the "identifier" as unique id, which is sent to the update server as-is.

i think the most clean way would be a patch folder in this repo, which will be applied and reverted by a dist/pack-script.
the first patch would replace:

`"identifier" : "payday2bltdll"`

with

`"identifier" : "payday2bltso"`

and

`"display_name" : "Payday 2 BLT Hook DLL"`

with

`"display_name" : "Payday 2 BLT Hook SO"`

..or similar.
and then you could host a zip with the steamrt-so as "payday2bltso" on paydaymods.com

or you could use even more id's for 3 different update-sources, like: "payday2bltso_steamrt","payday2bltso_stretch","payday2bltso_trusty"

instead of a patch-concept you could also "sed" those 2 lines.

**Comment by Ozymandias117** [comment] 2016-04-27 00:13
I mean, running sed after installing or updating is a pretty shitty workaround.

I'm not sure how adding a special case inside of something that is already, by definition, a special case is somehow "against the design of the BLT". However, we don't actually need that codepath at all, so it can be safely left in and ignored.

Really the best design would be to make the base BLT and the BLT DLL two separate mods.

**Comment by RomanHargrave** [comment] 2016-04-27 01:46
Marking invalid because it's not a part of blt4l causing the problem.

**Comment by RomanHargrave** [comment] 2016-04-27 01:50
@BangL my suggestion was to include both the SO/DLL entries in `mod.txt`, but add support for a `platform` key that the base mod understands. The value of that platform key would be `windows` or `linux` (or `mac`, if that ever happens). The host BLT would implement a `GetPlatform` script call which would return one of the two. Any entries in `mod.txt` not applicable to the platform are simply ignored.

This is a much cleaner solution, and fits in with using a shared LUA repo, unlike patching the base mod config, which (no offense) is an absolutely terrible idea, and defeats the purpose of the base mod living a repo separate from the Windows or Linux host.

**Comment by RomanHargrave** [comment] 2016-12-08 23:39
Closing wontfix/cantfix

**Closed by RomanHargrave** 2016-12-08 23:39 UTC
Labels: invalid
