### ISSUE TITLE
New feature for mod_overrides support

### ISSUE THREAD

**Issue by Kazenin** [blt4linux/blt4l#75] opened 2017-08-20 19:03 UTC
I would like to see AddFiles for BeardLib feature in BLT4L. An example below:

https://modworkshop.net/mydownloads.php?action=view_down&did=19760

Thank you so much

**Comment by RomanHargrave** [comment] 2017-08-21 00:10
Could you please describe AddFiles?

Additionally, if this has to do with adding asset DB entries, I have done some work reverse-engineering the DB internals, but haven't worked more on it lately.

If this requires the ability to modify asset DB state, this feature isn't easily added.

**Comment by Kazenin** [comment] 2017-08-21 00:59
For example, the mod that I put the link has an .xml file inside its directory and I realized that this type of texture is not working with the current version of BLT4L. On windows works perfectly. Please bring it down and take the test. It's a custom weapon.

**Comment by Kazenin** [comment] 2017-08-21 01:01
In addition, beardlib is required for this type of overrides

**Comment by RomanHargrave** [comment] 2017-08-21 01:04
Custom weapons need to modify the DB, which is something that, as far as I can tell, is not present in the Linux version of the game in any functional manner (unlike the case with mod_overrides).

So in order to support this, we would need to completely reverse engineer the internal structure of DB and MainDB, the two classes that handle the Diesel asset system. From what I can tell, it uses a system built with either std::tree or std::map, what is stored in them though, I am unsure.

**Comment by RomanHargrave** [comment] 2017-08-21 01:05
Duplicate of #70

**Closed by RomanHargrave** 2017-08-21 01:05 UTC
Labels: duplicate, wishlist
