### ISSUE TITLE
Failed reading hook file mod.lua of type post

### ISSUE THREAD

**Issue by TheFinestSurgeon** [blt4linux/blt4l#107] opened 2018-05-17 17:52 UTC
BeardLib & HoloUI both have this error

I have included a .zip of my mods folder 
[Mod + Loader.zip](https://github.com/blt4linux/blt4l/files/2014241/Mod.Loader.zip)

```
Info: finding lua functions
Info: installing hooks
Info: installing BLT LUA API
Info: Loading BLT Base
Info: Type: 4
Info: ref: 5
Info: installing BLT LUA API
Info: Loading BLT Base
[BLT] Setup...
[BLT] Loading module: 	BLTLogs
[BLT] Loading module: 	BLTModManager
[BLT] Loading module: 	BLTKeybindsManager
[BLT] Loading module: 	BLTPersistScripts
[BLT] Loading module: 	BLTLocalization
[BLT] Cleaning logs folder, lifetime 1 day(s)
[BLT] Loading mods for state: table: 0x01afc3c0
[BLT] Loading mod: Holo
[BLT] Loading mod: BeardLib
[BLT] Loading mod: base
[BLT] Loading mod: Linux IO Compat
[BLT] Setting up mod: 	base
[BLT] Setting up mod: 	Linux IO Compat
[BLT] Setting up mod: 	BeardLib
[BLT] Setting up mod: 	Holo
Info: Type: 4
Info: ref: 5
Info: installing BLT LUA API
Info: Loading BLT Base
[BLT] Setup...
[BLT] Loading module: 	BLTLogs
[BLT] Loading module: 	BLTModManager
[BLT] Loading module: 	BLTKeybindsManager
[BLT] Loading module: 	BLTPersistScripts
[BLT] Loading module: 	BLTLocalization
[BLT] Cleaning logs folder, lifetime 1 day(s)
[BLT] Loading mods for state: table: 0x01afc180
[BLT] Loading mod: Holo
[BLT] Loading mod: BeardLib
[BLT] Loading mod: base
[BLT] Loading mod: Linux IO Compat
[BLT] Setting up mod: 	base
[BLT] Setting up mod: 	Linux IO Compat
[BLT] Setting up mod: 	BeardLib
[BLT] Setting up mod: 	Holo
[BeardLib] [ERROR] Failed reading hook file mods/BeardLib/Hooks/KillzoneManager.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUDManager.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HUDHooks.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/PlayerCustody.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/AssaultCorner.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/PlayerDowned.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/Interaction.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/BlackScreen.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HUDHooks.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HeistTimer.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/Objectives.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HUDHooks.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HUDHooks.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/Teammate.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HUDHooks.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/Chat.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/Carry.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/Hint.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/HUD/HUDHooks.lua of type post
[HoloUI] [ERROR] Failed reading hook file mods/Holo/Hooks/Menu/BlackMarketGUI.lua of type post
[HoloUI] Loaded Textures
[HoloUI] Done Loading
```

**Comment by RomanHargrave** [comment] 2018-05-20 05:38
@TheFinestSurgeon 

This issue appears to be caused by case insensitive file naming habits or practices in HoloUI. I have opened an issue there for you.

If this issue persists later, please reopen it with information. For now I am closing it as responsibility is in the hands of Luffyyy (or you, or anyone interested) to fix HoloUI.

**Closed by RomanHargrave** 2018-05-20 05:38 UTC
Labels: lua-beardlib, lua-other-mods
