### ISSUE TITLE
dohttpreq problems.

### ISSUE THREAD

**Issue by simon-wh** [blt4linux/blt4l#29] opened 2016-06-07 01:36 UTC
It appears that for a semi-large file download ~20mb zip it ends up ending short, returning the downloaded data which is not complete. I've also noticed that it appears that it doesn't call the progress callback function when it's downloading the file. Or if it does call it, it doesn't call it with the correct data for the downloaded file, by that I'm referring to the downloaded and total bytes.

**Comment by Ozymandias117** [comment] 2016-06-08 03:20
Can give us the outdated mod that you were trying to update, or some way to reproduce the issue?

The incomplete data sounds like a bug, but I don't know how it's being hit from a cursory look at the code. The progress issue could be that the callback is never getting set. If the lua state isn't correct, we never set it up to be called. However, it's just as possible that it's a bug. Without something to test with, I don't know what's going on.

**Comment by RomanHargrave** [comment] 2016-06-08 03:50
Please provide the following, unless it is simply not possible to do so:

* Verbose blt4l output

* URL of the file experiencing the error

* Server logs from the server hosting the file, with irrelevant log information removed

If possible, please try hosting the file on a separate sever to see if the issue persists there. If it persists on a separate host, it is most likely a problem with BLT4L.

**Comment by GreatBigBushyBeard** [comment] 2016-06-08 15:41
I was experiencing the issue while downloading a file from LastBullet, the same issue also occurs for the same file on Paydaymods.com. I'm not exactly sure how to get the "Verbose blt4l output", I've tried adding '-x' as a parameter?. But due to the fact that I have steam running through console, I can see 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 66 20.5M   66 13.5M    0     0   231k      0  0:01:30  0:00:59  0:00:31  323k
04:33:44 PM Lua: Finished!
```
With the 'Finished' being from my finished callback on the http request. Here is the file url I'm using: http://download.paydaymods.com/download/latest/pdth_hud_mod_overrides

**Comment by RomanHargrave** [comment] 2016-06-08 19:16
Is this happening in the updater? Or is this in code you've written. If you've written it can you please provide an excerpt?

**Comment by RomanHargrave** [comment] 2016-06-08 19:27
Looking at the flow for the HTTP thread, a basic outline should like like 

```
[0]-> launch_request
[1]  -> launch_http_thread
[0]<-
[1]  ... (cURL setup)
[1]  -> curl_easy_perform
[1]    -> write_http_data 
[1]    <-
[1]  <- curl_easy_perform
[1]  -> curl_easy_cleanup
[1]  <- 
[1]  -> event->enqueue(... completion callback ...)
[1]  <-
[1]  <- launch_http_thread
```

So let me briefly ask, are you insuring that you are using the callback and not assuming that `dohttpreq` is blocking?

**Comment by RomanHargrave** [comment] 2016-06-08 19:36
@GreatBigBushyBeard quick update here.

Can you please run your code with the BLT4L from the [curl_error_state](https://github.com/blt4linux/blt4l/tree/curl_error_state) branch?

**Comment by GreatBigBushyBeard** [comment] 2016-06-08 21:02
I tried the curl_error_state branch, but it isn't showing anything different. It appears to be really consistent at lasting for 59 total seconds and never calling the progress callback.

This is the code I'm using:
`dohttpreq("download.paydaymods.com/download/latest/pdth_hud_mod_overrides", function(data, id)  log(tostring(string.len(data))) log("Finished!") end, function(...) log("progress") end)`

**Comment by RomanHargrave** [comment] 2016-06-08 21:39
Then code executed by `curl_easy_perform` is not causing the issue, and that callback seems to be getting called...

So the issue is somewhere between the server and cURL.

Can you get me a copy of the mod that contains that code so that I can run it?

**Comment by GreatBigBushyBeard** [comment] 2016-06-08 21:56
The code I'm using is exactly as I mentioned in my previous comment, set up in a keybind.

**Comment by RomanHargrave** [comment] 2016-06-08 22:01
Ah. I'll have to set it up in a bit and test it.

**Comment by RomanHargrave** [comment] 2016-06-09 17:54
@GreatBigBushyBeard I've just tested it and received the following output when using your snippet:

```
12:51:18 PM Lua: progress
12:51:23 PM Lua: 21499670
12:51:23 PM Lua: Finished!
```

A size of 21'499'670 bytes seems correct, and matches the file size when I download it using conventional means.

**Comment by GreatBigBushyBeard** [comment] 2016-06-09 17:58
Is taking longer than 59 seconds to download? Every time I try it, it ends at 59 seconds. Due to the fact that my internet is ridiculously slow, it takes some time to download things.

**Comment by RomanHargrave** [comment] 2016-06-09 18:00
Nope, it took less than ten. Could it be that paydaymods/lb are closing your connection?

**Comment by GreatBigBushyBeard** [comment] 2016-06-09 18:02
I doubt it, considering I can download the files just fine through chrome. At the exact same speeds.

**Comment by RomanHargrave** [comment] 2016-06-09 18:11
Then you are hitting the cURL timeout. It looks like `CURLOPT_TIMEOUT` was mistaken for `CURLOPT_CONNECTTIMEOUT` in BLT4Win (possibly, not sure). For now, I have made an according change in BLT4L.

**Comment by GreatBigBushyBeard** [comment] 2016-06-09 21:39
Using a version built from your changes, I am not able to actually download the file. However the progress callback is still never being called on my end.

**Comment by RomanHargrave** [comment] 2016-06-09 22:08
I set the connect timeout to 15 seconds. Perhaps try a higher value?

**Comment by GreatBigBushyBeard** [comment] 2016-06-09 22:20
Whoops, I made a typo in my comment. I meant to say that I am able to download the file.

**Comment by RomanHargrave** [comment] 2016-06-09 22:24
Has the progress callback ever been called? Or is this a new development?

**Comment by GreatBigBushyBeard** [comment] 2016-06-09 22:36
For me I've never had my progress callback called as far as I can tell/remember.

**Comment by RomanHargrave** [comment] 2016-06-09 23:33
OK

**Comment by RomanHargrave** [comment] 2016-06-10 01:08
07121d5 should fix the issue with the progress callback getting hit once

**Comment by RomanHargrave** [comment] 2016-06-10 21:28
@GreatBigBushyBeard can you please check to see if progress is working as expected? I've got updates working here.

**Comment by GreatBigBushyBeard** [comment] 2016-06-10 21:32
I'm still not getting any progress calls on my end.

**Comment by RomanHargrave** [comment] 2016-06-10 21:43
huh
at that commit? I'm getting one on average every 10ms. Do you know if your cURL version uses `PROGRESS_` or `XFERINFO_` curlopts?

**Comment by GreatBigBushyBeard** [comment] 2016-06-10 21:43
No idea, how can I check?

**Comment by RomanHargrave** [comment] 2016-06-10 21:44
cURL defines a macro, `LIBCURL_VERSION_NUM`.

**Comment by GreatBigBushyBeard** [comment] 2016-06-10 22:11
I've got libcurl 7.35.0 / 072300

**Comment by RomanHargrave** [comment] 2016-06-11 05:26
huh. that's really odd.

**Comment by RomanHargrave** [comment] 2016-12-08 23:40
Closing since issue topic is fixed, opening a separate issue for the broken callback.

**Closed by RomanHargrave** 2016-12-08 23:40 UTC
Labels: bug, fixed
